# Generated by Django 5.0.6 on 2024-06-24 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo Referência')),
                ('autor', models.CharField(blank=True, max_length=300, null=True, verbose_name='Autor')),
                ('year', models.PositiveIntegerField(verbose_name='Ano')),
                ('objectives', models.CharField(max_length=600, verbose_name='Objetivos')),
                ('database', models.CharField(max_length=150, verbose_name='Base de Dados')),
                ('results', models.CharField(max_length=600, verbose_name='Resultados')),
                ('limitations', models.CharField(max_length=600, verbose_name='Limitações')),
                ('referencies', models.CharField(max_length=600, verbose_name='Referencias')),
                ('dataacess', models.DateTimeField(auto_now=True, verbose_name='Data de Acesso')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category', verbose_name='Categoria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'db_table': 'registers',
            },
        ),
    ]
